# Generated by Django 3.1.1 on 2021-02-25 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_first_name', models.CharField(max_length=200)),
                ('off_last_name', models.CharField(max_length=200)),
                ('off_birth_date', models.DateField()),
                ('off_age', models.CharField(max_length=200)),
                ('off_gender', models.CharField(max_length=200)),
                ('off_race', models.CharField(max_length=200)),
                ('off_status', models.CharField(max_length=200)),
                ('off_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('off_updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NC_offender_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_off_id', models.CharField(max_length=200)),
                ('nc_off_experience', models.TextField()),
                ('nc_off_exp_status', models.CharField(max_length=200)),
                ('nc_off_exp_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nc_off_exp_updated_date', models.DateTimeField()),
                ('nc_off_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NC_Blocked_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_blocked_user_id', models.CharField(max_length=200)),
                ('nc_blocked_user_status', models.CharField(max_length=200)),
                ('nc_blocked_user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nc_blocked_user_updated_date', models.DateTimeField()),
                ('nc_blocked_user_first_name', models.CharField(max_length=200)),
                ('nc_blocked_user_last_name', models.CharField(max_length=200)),
                ('nc_blocked_user_dob', models.DateField()),
                ('nc_blocked_user_race', models.CharField(max_length=200)),
                ('nc_blocked_user_sex', models.CharField(max_length=200)),
                ('nc_blocked_user_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCS_offender_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcs_off_pid', models.CharField(max_length=200)),
                ('mcs_off_jid', models.CharField(max_length=200)),
                ('mcs_off_experience', models.TextField()),
                ('mcs_off_exp_status', models.CharField(max_length=200)),
                ('mcs_off_exp_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mcs_off_exp_updated_date', models.DateTimeField()),
                ('mcs_off_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCS_Blocked_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcs_blocked_user_pid', models.CharField(max_length=200)),
                ('mcs_blocked_user_jid', models.CharField(max_length=200)),
                ('mcs_blocked_user_status', models.CharField(max_length=200)),
                ('mcs_blocked_user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mcs_blocked_user_updated_date', models.DateTimeField()),
                ('mcs_blocked_user_first_name', models.CharField(max_length=200)),
                ('mcs_blocked_user_last_name', models.CharField(max_length=200)),
                ('mcs_blocked_user_dob', models.DateField()),
                ('mcs_blocked_user_race', models.CharField(max_length=200)),
                ('mcs_blocked_user_sex', models.CharField(max_length=200)),
                ('mcs_blocked_user_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.TextField()),
                ('security_answer', models.TextField()),
                ('motel_name', models.CharField(max_length=200, null=True)),
                ('motel_address', models.CharField(max_length=200, null=True)),
                ('motel_city', models.CharField(max_length=200, null=True)),
                ('motel_state', models.CharField(max_length=200, null=True)),
                ('motel_country', models.CharField(max_length=200, null=True)),
                ('motel_pincode', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_experience', models.TextField()),
                ('record_status', models.CharField(max_length=200)),
                ('record_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_updated_date', models.DateTimeField()),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offender.offender')),
                ('record_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blocked_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user_status', models.CharField(max_length=200)),
                ('blocked_user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_user_updated_date', models.DateTimeField()),
                ('blocked_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offender.offender')),
                ('blocked_user_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
