# Generated by Django 3.1.1 on 2021-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offender', '0002_auto_20210225_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc_blocked_user',
            name='nc_blocked_user_dob',
            field=models.CharField(max_length=200),
        ),
    ]
